export const categorias = [
    {nombre:"Pop"},
    {nombre:"Rock"},
    {nombre:"Rap"},
    {nombre:"Dembow"},
    {nombre:"Salsa"},
    {nombre:"Merengue"},
    {nombre:"Electrónica"},
    {nombre:"K-pop"},
    {nombre:"Reggaeton"},
    {nombre:"Folklórica"},
    {nombre:"Clásica"},
    {nombre:"Soundtrack de Videojuegos"},
    {nombre:"Trap"},
];