-- CreateTable
CREATE TABLE `PENE` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `culo` VARCHAR(191) NOT NULL,
    `teta` VARCHAR(191) NOT NULL,
    `password` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `PENE_teta_key`(`teta`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
